# Generated by Django 3.1.7 on 2021-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210322_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
