# Generated by Django 3.1.7 on 2021-03-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210322_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
    ]
